import propsJson from '../generated/props.json';

export interface DocProp {
  name: string;
  type: string;
  required: boolean;
  default: string | null;
  description: string;
}

export interface DocComponent {
  /** Source file, repo-relative. */
  file: string;
  description: string;
  props: DocProp[];
}

/** Props of every kit component, keyed by display name. Generated by `npm run site:docgen`. */
export const docgen: Record<string, DocComponent> = propsJson;

/** The entry's docgen names that have a props table. */
export const documented = (components: string[]) => components.filter((c) => c in docgen);
