#!/usr/bin/env node
// Regenerates src/index.ts from every src/components/*/index.ts (+ icons, utils, tokens).
//   npm run barrel
import { readdirSync, existsSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

const src = resolve(import.meta.dirname, '../src')
const components = readdirSync(resolve(src, 'components'), { withFileTypes: true })
  .filter((d) => d.isDirectory() && existsSync(resolve(src, 'components', d.name, 'index.ts')))
  .map((d) => d.name)
  .sort()

const lines = [
  '// Generated by scripts/build-barrel.mjs — do not edit by hand (npm run barrel).',
  "import './styles/tokens.css'",
  "import './styles/base.css'",
  '',
  "export * from './utils'",
  "export * from './icons'",
  "export { tokens } from './styles/tokens'",
  "export type { Tokens } from './styles/tokens'",
  '',
  ...components.map((c) => `export * from './components/${c}'`),
  '',
]
writeFileSync(resolve(src, 'index.ts'), lines.join('\n'))
console.log(`src/index.ts: ${components.length} component modules`)
