import type { Decorator, Preview } from '@storybook/react-vite'
import '../src/styles/fonts.css'
import '../src/styles/tokens.css'
import '../src/styles/base.css'
import './preview.css'
import './preview-docs.css'
import { configureArt } from '../examples/art'
import { zzzDocsTheme } from './zzzTheme'

/*
 * Game art in stories and examples is loaded BY URL at runtime: examples/art resolves names from the
 * committed manifest (examples/art/art-manifest.json, regenerated by `npm run art-manifest`) to images
 * on static.nanoka.cc and Enka.Network. No game-art image file is part of this Storybook or its static build.
 * Test hook: `iframe.html?…&artBase=<url>` points both sources at another host (a self-hosted mirror,
 * or an unreachable one to see the empty frames).
 */
try {
  const artBase = new URLSearchParams(window.location.search).get('artBase')
  if (artBase) configureArt({ nanokaBase: artBase, enkaBase: artBase })
} catch {
  /* no window.location (never in a browser): keep the default sources */
}

/**
 * Every story renders inside a `.zzz-theme` root so the design tokens and the
 * `--zzz-scale` multiplier apply. Use the "Scale" toolbar to preview density:
 * 0.7 = the library's web default (rem-based: md controls ~40 px at a 16 px root),
 * 1 = game density (1 design unit = 1 CSS px at a 16 px root).
 */
const withTheme: Decorator = (Story, context) => {
  const scale = context.globals.zzzScale ?? '0.7'
  const surface = context.parameters.zzzSurface ?? 'app'
  return (
    <div
      className={`zzz-theme sb-zzz-frame sb-zzz-frame--${surface}`}
      style={{ ['--zzz-scale' as string]: scale }}
      data-layout={context.parameters.layout ?? 'centered'}
    >
      <Story />
    </div>
  )
}

const preview: Preview = {
  decorators: [withTheme],
  // The toolbar UI for this global is the ZZZ Scale tool (addons/zzz-toolbar.tsx, registered by
  // manager.ts); manager.css hides the stock dropdown below, which is kept so the global stays
  // declared (and usable from a manager built without the reskin).
  globalTypes: {
    zzzScale: {
      description: 'Global UI density (--zzz-scale): 0.7 = web default, 1 = game density',
      toolbar: {
        title: 'Scale',
        icon: 'zoom',
        items: [
          { value: '0.5', title: '0.5× (compact)' },
          { value: '0.7', title: '0.7× (web default)' },
          { value: '1', title: '1× (game density)' },
          { value: '1.333', title: '1.333× (large)' },
        ],
        dynamicTitle: true,
      },
    },
  },
  initialGlobals: { zzzScale: '0.7' },
  parameters: {
    layout: 'centered',
    backgrounds: { disable: true },
    // Autodocs / MDX pages: the dark ZZZ theme (zzzTheme.ts) + the docs rules in preview.css.
    docs: { theme: zzzDocsTheme },
    controls: { expanded: true, matchers: { color: /(background|color)$/i } },
    a11y: { test: 'todo' },
    options: {
      storySort: {
        order: ['Introduction', 'Using this Storybook', 'Foundations', 'Primitives', 'Forms', 'Data Display', 'Inventory', 'Overlays', 'Shell', 'Game', 'Examples', '*'],
      },
    },
  },
}

export default preview
