/**
 * Real Zenless Zone Zero art for stories, example pages and the demo — loaded BY URL at runtime.
 *
 * One mode, real art only. The committed manifest (art-manifest.json, generated by
 * `npm run art-manifest` from the static.nanoka.cc indexes and the Enka.Network namecard index)
 * holds names, metadata and image keys; no image file is in the repository. Image URLs are
 * `<base> + <key>`, with one base per source (configureArt({ nanokaBase, enkaBase }) points them
 * at a self-hosted mirror). Zenless Zone Zero © HoYoverse.
 *
 * Loading / missing behaviour: the manifest is imported statically, so the store is `ready` from
 * the first render (no manifest fetch, no swap after load). Each image slot (ArtSlot) shows a
 * neutral skeleton until its bytes arrive and an empty frame if the URL is unreachable — never
 * imitation art. GameArtProvider pins `loading` / `ready` / `missing` for a subtree (tests, stories).
 *
 * The library (src/) never imports this file: its components take `src` / ReactNode slots.
 */
import { createContext, useContext, useState, useSyncExternalStore, type CSSProperties, type ReactNode } from 'react'
import bundledManifest from './art-manifest.json'
import { ArtSlot } from './ArtSlot'
import { hashSeed, type Seed } from './rng'

export type { ArtStatus } from './ArtSlot'
export type AgentCrop = 'circle' | 'select' | 'crop' | 'general' | 'full'
export type Rank = 'S' | 'A' | 'B'
export type ItemRarity = 's' | 'a' | 'b' | 'c'
export type ArtSource = 'nanoka' | 'enka'

export interface GameAgent {
  id: string
  name: string
  code: string
  rank: Rank | null
  element: string | null
  baseElement: string | null
  specialty: string | null
  faction: number
  /** Image keys relative to the nanoka base (null = not on the CDN). */
  images: Record<AgentCrop, string | null>
  /** Pixel size of the `full` crop (it varies per agent). */
  fullSize: [number, number]
  /** Enka namecard key (ImgCardRoleS####.png), relative to the enka base (null = no card). */
  namecard: string | null
}
export interface GameWEngine {
  id: string
  name: string
  rank: Rank | null
  specialty: string | null
  baseAtk: number
  advancedStat: string
  description: string
  image: string | null
  /** Only present when not 400×400. */
  size?: [number, number]
}
export interface GameDriveDiscSet {
  id: string
  name: string
  twoPiece: string
  fourPiece: string
  image: string | null
  /** Only present when not 152×152. */
  size?: [number, number]
}
export interface GameItem {
  id: string
  name: string
  rarity: ItemRarity | null
  category: string
  class: number
  iconName: string
  image: string | null
  size?: [number, number]
  /** Boss materials: a 2048 px animated spritesheet instead of an icon (`image` is null). */
  sprite?: { sheet: string; cell: number; cols: number }
}
export interface GameNamecard {
  /** e.g. 'ImgCardRoleS0001', 'ImgCardEvent05'. */
  id: string
  group: 'role' | 'event'
  /** The agent on a role namecard. */
  agentId?: string
  name?: string
  /** Key relative to the enka base. */
  image: string
  size?: [number, number]
}
export interface GameArtManifest {
  schema: number
  source: string
  version: string
  credits: string
  /** Default base URL per source; image keys are relative to these. */
  sources: Record<ArtSource, string>
  agents: GameAgent[]
  wEngines: GameWEngine[]
  driveDiscSets: GameDriveDiscSet[]
  items: GameItem[]
  namecards: GameNamecard[]
  icons: { elements: Record<string, string | null>; specialties: Record<string, string | null>; misc: Record<string, string | null> }
}

export type GameArtState =
  | { status: 'loading' | 'missing'; manifest: null }
  | { status: 'ready'; manifest: GameArtManifest }

/* ------------------------------------------------------------------ store */

const manifest = bundledManifest as unknown as GameArtManifest
const DEFAULT_BASES: Record<ArtSource, string> = {
  nanoka: manifest.sources?.nanoka ?? 'https://static.nanoka.cc/assets/zzz/',
  enka: manifest.sources?.enka ?? 'https://enka.network/ui/zzz/',
}

interface Store { state: GameArtState; bases: Record<ArtSource, string> }
let store: Store = { state: { status: 'ready', manifest }, bases: { ...DEFAULT_BASES } }
const listeners = new Set<() => void>()
const emit = () => listeners.forEach((l) => l())
const subscribe = (l: () => void) => { listeners.add(l); return () => { listeners.delete(l) } }
const getStore = () => store

const withSlash = (u: string) => (u.endsWith('/') ? u : `${u}/`)

/**
 * Point image URLs at another host per source (e.g. a self-hosted mirror of the same file names).
 * Omitted keys keep their current value; `null` restores the manifest default.
 */
export function configureArt(options: { nanokaBase?: string | null; enkaBase?: string | null }) {
  const bases = { ...store.bases }
  if (options.nanokaBase !== undefined) bases.nanoka = options.nanokaBase === null ? DEFAULT_BASES.nanoka : withSlash(options.nanokaBase)
  if (options.enkaBase !== undefined) bases.enka = options.enkaBase === null ? DEFAULT_BASES.enka : withSlash(options.enkaBase)
  store = { ...store, bases }
  hinted = false
  emit()
}

/** The manifest is bundled, so this resolves immediately. Kept so callers can await it. */
export function preloadGameArt(): Promise<GameArtManifest | null> {
  const s = store.state
  return Promise.resolve(s.status === 'ready' ? s.manifest : null)
}
/** Alias of preloadGameArt. */
export const loadGameArt = preloadGameArt

/** Absolute URL of a manifest image key (non-reactive; components use the hooks). */
export const gameArtUrl = (key: string, source: ArtSource = 'nanoka') => store.bases[source] + key

let hinted = false
function hintUnreachable(src: string) {
  if (hinted) return
  hinted = true
  console.info(`[zone examples] No game art at "${src.slice(0, src.lastIndexOf('/') + 1)}". Image slots render empty.`)
}
/** Test seam: re-arm the one-time console hint and restore the default bases. */
export function resetGameArtForTests() {
  hinted = false
  store = { state: { status: 'ready', manifest }, bases: { ...DEFAULT_BASES } }
  emit()
}

const GameArtContext = createContext<GameArtState | null>(null)

/** Pins the art state for its subtree (tests, stories: `loading`, `ready` with a fixture, `missing`). */
export function GameArtProvider({ state, children }: { state: GameArtState; children: ReactNode }) {
  return <GameArtContext.Provider value={state}>{children}</GameArtContext.Provider>
}

/** The three-state art status (+ manifest when ready). GameArtProvider takes precedence over the store. */
export function useGameArtState(): GameArtState {
  const pinned = useContext(GameArtContext)
  const s = useSyncExternalStore(subscribe, getStore, getStore)
  return pinned ?? s.state
}

/** The manifest when ready, else null. */
export function useGameArt(): GameArtManifest | null {
  const s = useGameArtState()
  return s.status === 'ready' ? s.manifest : null
}

function useArtUrl() {
  const { bases } = useSyncExternalStore(subscribe, getStore, getStore)
  return (key: string | null | undefined, source: ArtSource = 'nanoka') => (key ? bases[source] + key : null)
}

/* ------------------------------------------------------------------ lookups */

/** Deterministically pick an entry for a seed (so seeded pages get stable real art). */
export function pickBySeed<T>(list: readonly T[], seed: Seed, salt = ''): T {
  // Integer seeds walk the list in order (consecutive seeds never repeat); others hash.
  if (typeof seed === 'number' && Number.isInteger(seed)) return list[((seed % list.length) + list.length) % list.length]
  return list[hashSeed(seed, salt) % list.length]
}

type Query = { id?: string; seed?: Seed }
/** id, else seed (seed 0 when neither is given). An unknown id without a seed resolves to null. */
function lookup<T extends { id: string }>(list: readonly T[] | undefined, q: Query, salt: string): T | null {
  if (!list?.length) return null
  if (q.id !== undefined) {
    const hit = list.find((e) => e.id === q.id)
    if (hit) return hit
    if (q.seed === undefined) return null
  }
  return pickBySeed(list, q.seed ?? 0, salt)
}

export function useAgent(q: Query): GameAgent | null {
  return lookup(useGameArt()?.agents, q, 'agent')
}
export function useWEngine(q: Query): GameWEngine | null {
  return lookup(useGameArt()?.wEngines, q, 'wengine')
}
export function useDriveDiscSet(q: Query): GameDriveDiscSet | null {
  return lookup(useGameArt()?.driveDiscSets, q, 'disc')
}
/** By id, then exact name, then seed (seeds only pick items that have an icon). */
export function useItem(q: { id?: string; name?: string; seed?: Seed }): GameItem | null {
  const items = useGameArt()?.items
  if (!items?.length) return null
  if (q.id !== undefined) {
    const hit = items.find((i) => i.id === q.id)
    if (hit) return hit
  }
  if (q.name !== undefined) {
    const hit = items.find((i) => i.name === q.name)
    if (hit) return hit
  }
  if (q.seed === undefined && (q.id !== undefined || q.name !== undefined)) return null
  return pickBySeed(items.filter((i) => i.image), q.seed ?? 0, 'item')
}
/** By namecard id, then agentId, then seed within `group` (all groups when omitted). */
export function useNamecard(q: { id?: string; agentId?: string; group?: GameNamecard['group']; seed?: Seed }): GameNamecard | null {
  const cards = useGameArt()?.namecards
  if (!cards?.length) return null
  if (q.id !== undefined) {
    const hit = cards.find((n) => n.id === q.id)
    if (hit) return hit
  }
  if (q.agentId !== undefined) {
    const hit = cards.find((n) => n.agentId === q.agentId)
    if (hit) return hit
  }
  if (q.seed === undefined && (q.id !== undefined || q.agentId !== undefined)) return null
  const pool = q.group ? cards.filter((n) => n.group === q.group) : cards
  return pool.length ? pickBySeed(pool, q.seed ?? 0, 'namecard') : null
}

/* ------------------------------------------------------------------ image components */

/** Shared props of the image components. None has a fallback and none ever renders an `<svg>`. */
export interface GameImageProps {
  /** Real-art id. If omitted, `seed` picks one deterministically. */
  id?: string
  seed?: Seed
  /** Alt text. Default: the entry's name. Pass '' for decorative art. */
  alt?: string
  /**
   * Explicit object-fit, inline (beats any slot rule). Omit it to use the component default
   * (cover for agents except `full`, namecards; contain otherwise), which is emitted as `data-fit`
   * at zero specificity so the parent library component's own slot rule wins.
   */
  fit?: 'cover' | 'contain'
  /** CSS object-position, e.g. '50% 28%' for a face-weighted cover crop. */
  position?: string
  /** 'fill' (default): fills the parent. 'ratio': full width with the asset's aspect ratio reserved. */
  layout?: 'fill' | 'ratio'
  /** Above-the-fold art: eager loading + high fetch priority. */
  priority?: boolean
  /** On the `<picture>` wrapper. */
  className?: string
  style?: CSSProperties
}

const AGENT_SIZES: Record<Exclude<AgentCrop, 'full'>, [number, number]> = {
  circle: [142, 142],
  select: [256, 250],
  crop: [384, 384],
  general: [180, 64],
}
const FULL_FALLBACK: [number, number] = [1268, 1716]

/** Store-aware slot: status from the store/provider, one console hint when a URL is unreachable. */
function StoreSlot({ src, size, alt, defaultFit, p }: {
  src: string | null
  size: [number, number]
  alt: string
  defaultFit: 'cover' | 'contain'
  p: GameImageProps
}) {
  const { status } = useGameArtState()
  return (
    <ArtSlot
      src={src}
      status={status}
      width={size[0]}
      height={size[1]}
      alt={p.alt ?? alt}
      fit={p.fit}
      defaultFit={defaultFit}
      position={p.position}
      layout={p.layout}
      priority={p.priority}
      className={p.className}
      style={p.style}
      onImageError={hintUnreachable}
    />
  )
}

export function AgentImage({ crop = 'crop', ...p }: GameImageProps & { crop?: AgentCrop }) {
  const agent = useAgent(p)
  const url = useArtUrl()
  const size = crop === 'full' ? agent?.fullSize ?? FULL_FALLBACK : AGENT_SIZES[crop]
  return <StoreSlot src={url(agent?.images[crop])} size={size} alt={agent?.name ?? ''} defaultFit={crop === 'full' ? 'contain' : 'cover'} p={p} />
}

export function WEngineImage(p: GameImageProps) {
  const w = useWEngine(p)
  const url = useArtUrl()
  return <StoreSlot src={url(w?.image)} size={w?.size ?? [400, 400]} alt={w?.name ?? ''} defaultFit="contain" p={p} />
}

export function DriveDiscImage(p: GameImageProps) {
  const d = useDriveDiscSet(p)
  const url = useArtUrl()
  return <StoreSlot src={url(d?.image)} size={d?.size ?? [152, 152]} alt={d?.name ?? ''} defaultFit="contain" p={p} />
}

/** Item / material / currency icon: by `id`, then exact `name`, then `seed`. */
export function ItemImage({ name, ...p }: GameImageProps & { name?: string }) {
  const item = useItem({ id: p.id, name, seed: p.seed })
  const url = useArtUrl()
  return <StoreSlot src={url(item?.image)} size={item?.size ?? [156, 156]} alt={item?.name ?? ''} defaultFit="contain" p={p} />
}

/**
 * Enka.Network Inter-Knot namecard (≈4096×404 banner): by namecard `id`, then `agentId`, then
 * `seed` within `group`. Default fit cover, centred.
 */
export function NamecardImage({ agentId, group, ...p }: GameImageProps & { agentId?: string; group?: GameNamecard['group'] }) {
  const card = useNamecard({ id: p.id, agentId, group, seed: p.seed })
  const url = useArtUrl()
  return <StoreSlot src={url(card?.image, 'enka')} size={card?.size ?? [4096, 404]} alt={card?.name ? `${card.name} namecard` : ''} defaultFit="cover" p={p} />
}

/**
 * Game element / specialty / currency icon.
 *  - loading: an empty `<span>` with the same className/style (the parent's sizing applies; no fallback).
 *  - ready: the icon in an ArtSlot.
 *  - missing, this icon is null (e.g. Lumiflux), or its URL failed: `fallback` (e.g. a src/icons SVG).
 */
export function GameIcon({ kind, name, fallback = null, alt, className, style }: {
  kind: 'elements' | 'specialties' | 'misc'
  name: string
  fallback?: ReactNode
  alt?: string
  className?: string
  style?: CSSProperties
}) {
  const s = useGameArtState()
  const url = useArtUrl()
  const [failed, setFailed] = useState<string | null>(null)
  if (s.status === 'loading') return <span aria-hidden className={className} style={style} />
  const src = s.status === 'ready' ? url(s.manifest.icons[kind][name]) : null
  if (!src || failed === src) return <>{fallback}</>
  return (
    <ArtSlot
      src={src}
      width={96}
      height={96}
      alt={alt ?? ''}
      defaultFit="contain"
      className={className}
      style={style}
      onImageError={(u) => { hintUnreachable(u); setFailed(u) }}
    />
  )
}
